"""SAPT Attentive Reflection Module (ARM).

After training task t, ARM trains the shared-attention router on
pseudo-samples generated by each prior expert and the just-trained one.
For each task i in 1..t we generate a small pool of samples by activating
adapter i and running the model in generation mode from a small set of
seed prompts cached from task i's training data. Each pseudo-sample is
labelled with its source task; the router is trained with cross-entropy
over those task labels.

This is the faithful SAPT variant: no real samples from prior tasks are
required at ARM time — only the LoRA weights from those tasks plus a few
short prompt strings cached at the time the task was trained.
"""
from __future__ import annotations

import logging
import random
from typing import Dict, List, Optional

import torch
import torch.nn as nn
import torch.nn.functional as F

logger = logging.getLogger("cl_lora.sapt.arm")


def generate_pseudo_samples_for_task(
    peft_model: nn.Module,
    tokenizer,
    *,
    adapter_name: str,
    seed_prompts: List[str],
    n_samples: int,
    max_new_tokens: int,
    max_input_length: int,
    rng: random.Random,
) -> List[Dict[str, torch.Tensor]]:
    """Generate `n_samples` (input_ids, attention_mask) pairs from one expert.

    Activates only `adapter_name` and runs `model.generate` from sampled
    seed prompts. The returned tensors are CPU; device placement is done
    by the ARM training loop.
    """
    if not seed_prompts:
        raise ValueError(f"no seed prompts available for adapter {adapter_name!r}")

    peft_model.eval()
    try:
        peft_model.set_adapter(adapter_name)
    except Exception as exc:
        logger.warning("ARM: set_adapter(%s) failed: %s", adapter_name, exc)

    samples: List[Dict[str, torch.Tensor]] = []
    device = next(peft_model.parameters()).device
    for _ in range(int(n_samples)):
        prompt = seed_prompts[rng.randrange(len(seed_prompts))]
        enc = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=max_input_length,
        )
        input_ids = enc["input_ids"].to(device)
        attention_mask = enc.get("attention_mask")
        if attention_mask is not None:
            attention_mask = attention_mask.to(device)
        with torch.no_grad():
            try:
                gen = peft_model.generate(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    max_new_tokens=int(max_new_tokens),
                    do_sample=True,
                    temperature=1.0,
                    top_p=0.95,
                    pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,
                )
            except Exception as exc:
                logger.warning("ARM: generation failed for %s: %s; falling back to prompt only", adapter_name, exc)
                gen = input_ids
        gen_cpu = gen[0].detach().to("cpu")
        am_cpu = torch.ones_like(gen_cpu, dtype=torch.long)
        samples.append({"input_ids": gen_cpu, "attention_mask": am_cpu})
    return samples


def _pad_and_stack(samples: List[Dict[str, torch.Tensor]], pad_id: int) -> Dict[str, torch.Tensor]:
    max_len = max(int(s["input_ids"].shape[0]) for s in samples)
    B = len(samples)
    input_ids = torch.full((B, max_len), pad_id, dtype=torch.long)
    attn = torch.zeros((B, max_len), dtype=torch.long)
    for i, s in enumerate(samples):
        L = int(s["input_ids"].shape[0])
        input_ids[i, :L] = s["input_ids"]
        attn[i, :L] = s.get("attention_mask", torch.ones(L, dtype=torch.long))
    return {"input_ids": input_ids, "attention_mask": attn}


def train_router_arm(
    *,
    peft_model: nn.Module,
    router: nn.Module,
    tokenizer,
    seed_prompts_by_adapter: Dict[str, List[str]],
    adapter_names: List[str],
    n_samples_per_task: int,
    max_new_tokens: int,
    max_input_length: int,
    n_epochs: int,
    batch_size: int,
    learning_rate: float,
    seed: int,
) -> Dict[str, float]:
    """Run ARM: generate pseudo-samples per task, then train the router.

    Returns a small stats dict (loss, accuracy) for logging.
    """
    if router.n_tasks != len(adapter_names):  # type: ignore[attr-defined]
        raise RuntimeError(
            f"router.n_tasks={router.n_tasks} != adapter_names={len(adapter_names)}; "
            "did you forget to call router.add_task() before ARM?"
        )

    rng = random.Random(seed)
    device = next(peft_model.parameters()).device
    pad_id = int(tokenizer.pad_token_id or tokenizer.eos_token_id or 0)

    # Phase 1: generate pseudo-samples per adapter.
    logger.info(
        "ARM phase 1 (pseudo-sample generation): adapters=%d n_per_task=%d max_new_tokens=%d",
        len(adapter_names), n_samples_per_task, max_new_tokens,
    )
    pseudo: List[Dict[str, torch.Tensor]] = []
    labels: List[int] = []
    for col, name in enumerate(adapter_names):
        prompts = seed_prompts_by_adapter.get(name, [])
        if not prompts:
            logger.warning("ARM: no seed prompts cached for %s; skipping its pseudo-samples", name)
            continue
        try:
            samples = generate_pseudo_samples_for_task(
                peft_model,
                tokenizer,
                adapter_name=name,
                seed_prompts=prompts,
                n_samples=n_samples_per_task,
                max_new_tokens=max_new_tokens,
                max_input_length=max_input_length,
                rng=rng,
            )
        except Exception as exc:
            logger.warning("ARM: pseudo-sample generation failed for %s: %s", name, exc)
            continue
        pseudo.extend(samples)
        labels.extend([col] * len(samples))

    if not pseudo:
        logger.warning("ARM: no pseudo-samples gathered; skipping router training")
        return {"loss": float("nan"), "accuracy": float("nan"), "n_samples": 0}

    # Phase 2: router training.
    embed_layer = peft_model.get_input_embeddings()
    router.train()
    router.to(device)
    optim = torch.optim.AdamW(router.parameters(), lr=float(learning_rate))

    n_samples = len(pseudo)
    n_tasks = len(adapter_names)
    indices = list(range(n_samples))
    final_loss = float("nan")
    final_acc = float("nan")
    logger.info(
        "ARM phase 2 (router training): samples=%d tasks=%d epochs=%d bs=%d lr=%g",
        n_samples, n_tasks, n_epochs, batch_size, learning_rate,
    )

    for epoch in range(int(n_epochs)):
        rng.shuffle(indices)
        total = 0.0
        correct = 0
        seen = 0
        for start in range(0, n_samples, int(batch_size)):
            chunk = indices[start : start + int(batch_size)]
            batch_samples = [pseudo[i] for i in chunk]
            batch_labels = torch.tensor([labels[i] for i in chunk], dtype=torch.long, device=device)
            stacked = _pad_and_stack(batch_samples, pad_id=pad_id)
            input_ids = stacked["input_ids"].to(device)
            attn = stacked["attention_mask"].to(device)
            with torch.no_grad():
                embeds = embed_layer(input_ids)
            weights = router(embeds, attention_mask=attn)  # (B, n_tasks)
            # Cross-entropy on log-probs (router emits a softmax already).
            log_probs = (weights.clamp_min(1e-12)).log()
            loss = F.nll_loss(log_probs, batch_labels)
            optim.zero_grad(set_to_none=True)
            loss.backward()
            optim.step()
            total += float(loss.item()) * batch_labels.shape[0]
            correct += int((weights.argmax(dim=-1) == batch_labels).sum().item())
            seen += int(batch_labels.shape[0])
        final_loss = total / max(1, seen)
        final_acc = correct / max(1, seen)
        logger.info("ARM epoch %d/%d: loss=%.4f acc=%.4f", epoch + 1, int(n_epochs), final_loss, final_acc)

    router.eval()
    return {
        "loss": float(final_loss),
        "accuracy": float(final_acc),
        "n_samples": int(n_samples),
        "n_tasks": int(n_tasks),
    }


__all__ = ["generate_pseudo_samples_for_task", "train_router_arm"]
