"""SAPT — Shared Attention for Parameter-Efficient Continual Learning.

Zhao et al., "SAPT: A Shared Attention Framework for Parameter-Efficient
Continual Learning of Large Language Models" (ACL 2024).

This is a faithful integration: each task keeps a separate live LoRA expert
(no merging across stages); a shared-attention router routes inputs to
weighted combinations of experts; ARM (Attentive Reflection Module)
trains the router on pseudo-samples generated by each prior expert.

The CL method is responsible for:
  * declaring `requires_no_merge=True` so the orchestrator skips
    `merge_and_unload` between stages and instead keeps adapters parallel;
  * caching a small set of seed prompts per task (post_train);
  * after the new adapter is trained, growing the router by one task,
    generating pseudo-samples and running ARM to update the router weights;
  * persisting router state, task keys, and seed prompt strings to
    `cl_state/sapt/`.

Slice / LoRA-GA / LoRAM / vanilla init all compose with SAPT, but slice's
in-place absorption into base weights would compound across stages with
no merge. The orchestrator forces `slice_skip_absorption=True` whenever
`cl_method=sapt` to keep the base pristine.
"""
from __future__ import annotations

import logging
import os
import random
from typing import Any, Dict, List, Optional

import torch

from .base import CLMethod

logger = logging.getLogger("cl_lora.cl_methods.sapt")


class SAPTMethod(CLMethod):
    name = "sapt"
    requires_no_merge: bool = True
    requires_skip_absorption: bool = True

    def __init__(
        self,
        *,
        key_dim: int = 64,
        arm_n_samples_per_task: int = 64,
        arm_max_new_tokens: int = 32,
        arm_max_input_length: int = 128,
        arm_n_epochs: int = 3,
        arm_batch_size: int = 4,
        arm_learning_rate: float = 1e-3,
        seed_prompts_per_task: int = 32,
        seed: int = 42,
        **kwargs: Any,
    ) -> None:
        super().__init__(
            key_dim=key_dim,
            arm_n_samples_per_task=arm_n_samples_per_task,
            arm_max_new_tokens=arm_max_new_tokens,
            arm_max_input_length=arm_max_input_length,
            arm_n_epochs=arm_n_epochs,
            arm_batch_size=arm_batch_size,
            arm_learning_rate=arm_learning_rate,
            seed_prompts_per_task=seed_prompts_per_task,
            seed=seed,
            **kwargs,
        )
        self.key_dim = int(key_dim)
        self.arm_n_samples_per_task = int(arm_n_samples_per_task)
        self.arm_max_new_tokens = int(arm_max_new_tokens)
        self.arm_max_input_length = int(arm_max_input_length)
        self.arm_n_epochs = int(arm_n_epochs)
        self.arm_batch_size = int(arm_batch_size)
        self.arm_learning_rate = float(arm_learning_rate)
        self.seed_prompts_per_task = int(seed_prompts_per_task)
        self.seed = int(seed)
        # adapter_names[i] is the canonical PEFT adapter name for task i+1
        # (1-based stage). We use the standard "task_NN" format throughout.
        self.adapter_names: List[str] = []
        # Seed prompts cached at the time of each stage, used as launch points
        # for pseudo-sample generation during ARM at later stages.
        self.seed_prompts: Dict[str, List[str]] = {}
        # Router lives on disk under cl_state/sapt/router.pt; we hold a
        # serialized state-dict in memory for resume.
        self._router_packed: Optional[Dict[str, Any]] = None
        # Stats from the most recent ARM run (telemetry only).
        self.last_arm_stats: Optional[Dict[str, float]] = None

    # ---- orchestrator-facing accessors ----

    @staticmethod
    def adapter_name_for_stage(stage_idx: int) -> str:
        return f"task_{int(stage_idx):02d}"

    def all_adapter_names(self) -> List[str]:
        return list(self.adapter_names)

    # ---- standard CLMethod hooks (most are no-ops; SAPT runs out-of-band) ----

    def pre_train(self, lora_model, *, stage_idx, retain_tasks) -> None:
        # SAPT does not modify the new adapter at init time; the orchestrator
        # has already arranged for parallel loading + slice-no-absorb.
        return None

    def aux_loss(self, lora_model):
        return None

    def post_train(
        self,
        lora_model,
        *,
        tokenizer,
        train_dataset,
        device,
        stage_idx,
        task_name,
    ) -> None:
        """Cache a seed-prompt pool from this task's training data.

        We pull the raw `prompt` field if the dataset still carries it; otherwise
        we re-decode `input_ids` skipping special tokens. These prompts are
        used during ARM as launch points for adapter-specific generation.
        """
        adapter_name = self.adapter_name_for_stage(stage_idx)
        if adapter_name not in self.adapter_names:
            self.adapter_names.append(adapter_name)
        prompts = self._extract_seed_prompts(train_dataset, tokenizer, k=self.seed_prompts_per_task)
        self.seed_prompts[adapter_name] = prompts
        logger.info(
            "SAPT post_train: stage=%d adapter=%s seed_prompts=%d",
            stage_idx, adapter_name, len(prompts),
        )

    @staticmethod
    def _extract_seed_prompts(train_dataset, tokenizer, k: int) -> List[str]:
        if train_dataset is None or len(train_dataset) == 0:
            return []
        rng = random.Random(0)
        n = len(train_dataset)
        idxs = rng.sample(range(n), k=min(int(k), n))
        prompts: List[str] = []
        for i in idxs:
            row = train_dataset[i]
            text: Optional[str] = None
            if isinstance(row, dict):
                if "prompt" in row and isinstance(row["prompt"], str):
                    text = row["prompt"]
                elif "text" in row and isinstance(row["text"], str):
                    text = row["text"]
                elif "input_ids" in row:
                    ids = row["input_ids"]
                    if isinstance(ids, list):
                        ids = torch.tensor(ids, dtype=torch.long)
                    text = tokenizer.decode(ids, skip_special_tokens=False)
            if text:
                prompts.append(text)
        return prompts

    # ---- SAPT-specific entry: orchestrator calls this after each stage ----

    def run_arm(
        self,
        peft_model,
        tokenizer,
    ) -> Optional[Dict[str, float]]:
        """Build/grow the router and run ARM on pseudo-samples."""
        from ..sapt.arm import train_router_arm
        from ..sapt.router import SAPTRouter

        if not self.adapter_names:
            logger.warning("SAPT.run_arm called with no adapters; nothing to do.")
            return None

        # Build / restore router with one key per existing task, then add a
        # fresh key for any new tasks not yet represented.
        hidden_dim = self._infer_hidden_dim(peft_model)
        router = self._materialize_router(hidden_dim=hidden_dim)
        while router.n_tasks < len(self.adapter_names):
            router.add_task()
        router.to(next(peft_model.parameters()).device)

        # If only one task exists, ARM is degenerate (one-class softmax) but
        # we still run it so the optimizer state and shapes are consistent.
        stats = train_router_arm(
            peft_model=peft_model,
            router=router,
            tokenizer=tokenizer,
            seed_prompts_by_adapter=self.seed_prompts,
            adapter_names=list(self.adapter_names),
            n_samples_per_task=self.arm_n_samples_per_task,
            max_new_tokens=self.arm_max_new_tokens,
            max_input_length=self.arm_max_input_length,
            n_epochs=self.arm_n_epochs,
            batch_size=self.arm_batch_size,
            learning_rate=self.arm_learning_rate,
            seed=self.seed,
        )
        self._router_packed = router.state_dict_packed()
        self.last_arm_stats = stats
        logger.info("SAPT ARM stats: %s", stats)
        return stats

    # ---- router (de)serialization ----

    def _infer_hidden_dim(self, peft_model) -> int:
        embed = peft_model.get_input_embeddings()
        weight = getattr(embed, "weight", None)
        if weight is None:
            raise RuntimeError("Cannot infer hidden_dim from model embeddings.")
        return int(weight.shape[-1])

    def _materialize_router(self, hidden_dim: int):
        from ..sapt.router import SAPTRouter

        if self._router_packed is not None:
            return SAPTRouter.from_packed(self._router_packed)
        return SAPTRouter(hidden_dim=hidden_dim, n_tasks=0, key_dim=self.key_dim)

    def get_router_packed(self) -> Optional[Dict[str, Any]]:
        return self._router_packed

    # ---- persistence ----

    def save(self, state_dir: str) -> None:
        sapt_dir = os.path.join(state_dir, "sapt")
        os.makedirs(sapt_dir, exist_ok=True)
        payload = {
            "key_dim": self.key_dim,
            "arm": {
                "n_samples_per_task": self.arm_n_samples_per_task,
                "max_new_tokens": self.arm_max_new_tokens,
                "max_input_length": self.arm_max_input_length,
                "n_epochs": self.arm_n_epochs,
                "batch_size": self.arm_batch_size,
                "learning_rate": self.arm_learning_rate,
                "seed": self.seed,
            },
            "adapter_names": list(self.adapter_names),
            "seed_prompts": dict(self.seed_prompts),
            "router": self._router_packed,
            "last_arm_stats": self.last_arm_stats,
        }
        torch.save(payload, os.path.join(sapt_dir, "sapt_state.pt"))
        if self._router_packed is not None:
            # Canonical file — overwritten each stage; kept for backward compat / resume.
            torch.save(self._router_packed, os.path.join(sapt_dir, "router.pt"))
            # Per-stage snapshot so every stage can be evaluated independently.
            n = len(self.adapter_names)
            torch.save(self._router_packed, os.path.join(sapt_dir, f"router_stage_{n:02d}.pt"))

    def load(self, state_dir: str) -> None:
        path = os.path.join(state_dir, "sapt", "sapt_state.pt")
        if not os.path.exists(path):
            return
        payload = torch.load(path, map_location="cpu", weights_only=False)
        self.key_dim = int(payload.get("key_dim", self.key_dim))
        arm_cfg = payload.get("arm", {})
        self.arm_n_samples_per_task = int(arm_cfg.get("n_samples_per_task", self.arm_n_samples_per_task))
        self.arm_max_new_tokens = int(arm_cfg.get("max_new_tokens", self.arm_max_new_tokens))
        self.arm_max_input_length = int(arm_cfg.get("max_input_length", self.arm_max_input_length))
        self.arm_n_epochs = int(arm_cfg.get("n_epochs", self.arm_n_epochs))
        self.arm_batch_size = int(arm_cfg.get("batch_size", self.arm_batch_size))
        self.arm_learning_rate = float(arm_cfg.get("learning_rate", self.arm_learning_rate))
        self.seed = int(arm_cfg.get("seed", self.seed))
        self.adapter_names = list(payload.get("adapter_names", []))
        self.seed_prompts = dict(payload.get("seed_prompts", {}))
        self._router_packed = payload.get("router")
        self.last_arm_stats = payload.get("last_arm_stats")
        logger.info(
            "SAPT state loaded: adapters=%d seed_prompt_pools=%d router=%s",
            len(self.adapter_names), len(self.seed_prompts), bool(self._router_packed),
        )

    def metadata(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "key_dim": int(self.key_dim),
            "arm_n_samples_per_task": int(self.arm_n_samples_per_task),
            "arm_max_new_tokens": int(self.arm_max_new_tokens),
            "arm_n_epochs": int(self.arm_n_epochs),
            "n_adapters": len(self.adapter_names),
            "router_present": bool(self._router_packed is not None),
            "last_arm_stats": self.last_arm_stats,
        }
